version: '3'

services:
  ha:
    image: homeassistant/raspberrypi4-homeassistant
    environment:
      TZ: Australia/Melbourne
    volumes:
      - ~/.homeassistant:/config
    network_mode: host
    restart: always
