lights:
  name: Lights
  entities:
  - light.bathroom
  - light.bedroom
  - light.entry
  - light.guestroom
  - light.hall
  - light.lounge_front
  - light.lounge_rear
  - light.office

overrides:
  name: Disable
  entities: 
  - input_boolean.disable_auto_lights
  - input_boolean.disable_auto_motion
  - input_boolean.disable_auto_presence

garage_group:
  name: Garage Switches
  control: hidden
  entities:
    - switch.garage_light_switch
    - cover.the_bat_cave

garage:
  name: Garage
  view: true
  icon: mdi:garage
  entities:
    - group.garage_group
    - group.garage_sensors

netatmo_indoor:
  name: Netatmo Indoor
  entities:
  - sensor.netatmo_indoor_temperature
  - sensor.netatmo_indoor_humidity
  - sensor.netatmo_indoor_co2
  - sensor.netatmo_indoor_noise
  - sensor.netatmo_indoor_pressure
  
netatmo_outdoor:
  name: Netatmo Outdoor
  entities:
  - sensor.netatmo_outdoor_temperature
  - sensor.netatmo_outdoor_humidity
  - sensor.netatmo_outdoor_battery
  - sensor.netatmo_outdoor_radio
  - sun.sun

ring:
  name: Doorbell
  entities:
  - sensor.ring_front_door_horseshoe_cct_battery
  - sensor.ring_front_door_horseshoe_cct_last_activity
  - sensor.ring_front_door_horseshoe_cct_last_ding
  - sensor.ring_front_door_horseshoe_cct_last_motion
  - sensor.ring_front_door_horseshoe_cct_volume
  - camera.front_door_horseshoe_cct
  - sensor.ring_kitchen_volume

wunderground:
  name: Weather Underground
  entities:
  - sensor.pws_temp_c
  - sensor.pws_relative_humidity
  - sensor.pws_feelslike_c
  - sensor.pws_weather
  - sensor.pws_wind_dir
  - sensor.pws_wind_kph
  - sensor.pws_wind_gust_kph
  - sensor.pws_alerts
  - sensor.pws_location
  - sensor.pws_observation_time
  - sensor.pws_visibility_km
  - sensor.pws_heat_index_c
  - sensor.pws_dewpoint_c
  - sensor.pws_elevation
  - sensor.pws_precip_1hr_metric
  - sensor.pws_precip_today_metric
  - sensor.pws_pressure_mb
  - sensor.pws_pressure_trend
  - sensor.pws_station_id
  - sensor.pws_solarradiation
  - sensor.pws_uv
  - sensor.pws_wind_degrees

living_room:
  name: Living Room Lights
  entities:
  - light.lounge_front
  - light.lounge_rear

bedroom:
  name: Bedroom
  icon: mdi:hotel
  view: true
  entities:
  - light.bedroom
  - switch.air_conditioner
  - group.netatmo_indoor
  - group.jon

office_sensors:
  name: Office Sensors
  entities:
  - sensor.office_temperature
  - sensor.office_humidity
  - binary_sensor.motion_sensor_158d0001d92086

office_view:
  name: Office
  view: true
  icon: mdi:desktop-mac
  entities:
  - light.office
  - switch.wake_on_lan
  - group.office_sensors

harmony:
  name: Harmony
  entities:
  - sensor.living_room_activity
  - input_select.harmony

dyson_fan:
  name: Dyson Pure Hot+Cool
  entities:
  - fan.pure_hotcool
  - sensor.pure_hotcool_temperature
  - sensor.pure_hotcool_humidity
 
living_room_view:
  name: Living Room
  icon: mdi:sofa
  view: yes
  entities:
  - camera.livingroom_camera
  - group.living_room
  - group.harmony
  - media_player.integra
  - media_player.shield
  - media_player.shield_android_tv
  - media_player.plex
  - media_player.blackmagic
  - group.dyson_fan
  - group.ups
  - group.xiaomi_gateway

xiaomi_gateway:
  name: Xiaomi Gateway
  icon: mdi:router-wireless
  entities:
  - sensor.illumination_7811dc6c8ece
  - light.gateway_light_7811dc6c8ece

weather_view:
  name: Weather
  icon: mdi:cloud
  view: yes
  entities:
  - group.netatmo_indoor
  - group.entry_sensors
  - group.office_sensors
  - group.garage_sensors
  - group.netatmo_outdoor
  - group.wunderground  

cameras_view:
  name: Cameras
  icon: mdi:camera
  view: yes
  entities:
  - camera.livingroom_camera
  - camera.last_ring_video

entry_sensors:
  name: Entry Sensors
  entities:
  - sensor.aeotec_zw100_multisensor_6_burglar
  - sensor.aeotec_multisensor_motion_template_1
  - sensor.aeotec_zw100_multisensor_6_luminance
  - sensor.aeotec_zw100_multisensor_6_relative_humidity
  - sensor.aeotec_zw100_multisensor_6_temperature
  - sensor.aeotec_zw100_multisensor_6_ultraviolet

garage_sensors:
  name: Garage Sensors
  entities:
  - sensor.garage_door_status
  - sensor.garage_door_state
  - sensor.aeotec_zw100_multisensor_6_usb_burglar
  - sensor.aeotec_zw100_multisensor_6_usb_luminance
  - sensor.aeotec_zw100_multisensor_6_usb_relative_humidity
  - sensor.aeotec_zw100_multisensor_6_usb_temperature
  - sensor.aeotec_zw100_multisensor_6_usb_ultraviolet

jon:
  name: Jon
  entities:
  - device_tracker.jon_mobile
  - binary_sensor.jon_sleeping

laundry_group:
  name: Laundry
  entities:
  - switch.plug_158d00019d0f86
  - binary_sensor.door_window_sensor_158d0001c2e60e
  
laundry_view:
  name: Laundry
  icon: mdi:washing-machine
  view: yes
  entities:
  - group.laundry_group

overview:
  name: ' Overview'
  entities:
  - sensor.netatmo_indoor_temperature
  - sensor.netatmo_indoor_humidity
  - switch.air_conditioner
  - sensor.aeotec_zw100_multisensor_6_burglar
  - sensor.garage_door_status
  - sensor.garage_door_state
  - cover.the_bat_cave
  - sensor.aeotec_zw100_multisensor_6_usb_burglar
  - sensor.aeotec_zw100_multisensor_6_usb_temperature
  - sensor.aeotec_zw100_multisensor_6_usb_relative_humidity
  
ups:
  name: UPS
  icon: mdi:battery
  entities:
  - sensor.nut_ups_status_data
  - sensor.nut_ups_load
  - sensor.nut_ups_nominal_real_power
  - sensor.nut_ups_battery_charge
  - sensor.nut_ups_battery_runtime
  - sensor.nut_ups_low_battery_runtime
  - sensor.nut_ups_battery_temperature
  - sensor.nut_ups_battery_voltage
  - sensor.nut_ups_nominal_battery_voltage
  - sensor.nut_ups_input_voltage
  - sensor.nut_ups_nominal_input_voltage

bathroom_sensors:
  name: Bathroom Sensors
  entities:
  - sensor.temperature_158d0001fead1f
  - sensor.humidity_158d0001fead1f

bathroom_view:
  name: Bathroom
  icon: mdi:human-male-female
  view: yes
  entities:
  - light.bathroom
  - group.bathroom_sensors

zigbee_group:
  name: To Sort
  icon: mdi:router-wireless
  entities:
  - binary_sensor.switch_158d0001d8dbde
  - binary_sensor.wall_switch_both_158d0001641a34
  - binary_sensor.wall_switch_left_158d0001641a34
  - binary_sensor.wall_switch_right_158d0001641a34
  - binary_sensor.smoke_sensor_158d0001641a34
  - light.aeotec_led_bulb_level

default_view:
  name: Home
  icon: mdi:home
  view: yes
  entities:
  - group.overview
  - group.jon
  - group.lights
  - group.dyson_fan
  - group.zigbee_group
  - group.alarm

alarm:
  name: Alarm Panel
  entities:
  - alarm_control_panel.home_alarm

automation:
  name: Automation
  view: yes
  icon: mdi:auto-fix
  entities:
   - group.all_scenes
   - group.all_automations
   - group.all_scripts
   - group.overrides

