lights:
  name: Lights
  entities:
  - light.entry_light_level
  - light.bathroom
  - light.bedroom
  - light.kitchen
  - light.coffee_table
  - light.dining_table
  - light.rear
  - light.office
  - light.hall
  - light.laundry
  - light.guestroom
  - light.gateway_light_7811dc6c8ece

overrides:
  name: Disable
  entities: 
  - input_boolean.disable_auto_lights
  - input_boolean.disable_auto_motion
  - input_boolean.disable_auto_presence

garage_group:
  name: Garage Switches
  entities:
    - switch.garage_light_switch
    - cover.the_bat_cave
    - camera.garage

netatmo_indoor:
  name: Netatmo Indoor
  entities:
  - sensor.netatmo_indoor_temperature
  - sensor.netatmo_indoor_humidity
  - sensor.netatmo_indoor_co2
  - sensor.netatmo_indoor_noise
  - sensor.netatmo_indoor_pressure
  
netatmo_outdoor:
  name: Netatmo Outdoor
  entities:
  - sensor.netatmo_outdoor_temperature
  - sensor.netatmo_outdoor_humidity
  - sensor.netatmo_outdoor_battery
  - sensor.netatmo_outdoor_radio
  - sun.sun

ring:
  name: Doorbell
  entities:
  - sensor.ring_front_door_horseshoe_cct_battery
  - sensor.ring_front_door_horseshoe_cct_last_activity
  - sensor.ring_front_door_horseshoe_cct_last_ding
  - sensor.ring_front_door_horseshoe_cct_last_motion
  - sensor.ring_front_door_horseshoe_cct_volume
  - camera.front_door_horseshoe_cct
  - sensor.ring_kitchen_volume

wunderground:
  name: Weather Underground
  entities:
  - sensor.pws_temp_c
  - sensor.pws_relative_humidity
  - sensor.pws_feelslike_c
  - sensor.pws_weather
  - sensor.pws_wind_dir
  - sensor.pws_wind_kph
  - sensor.pws_wind_gust_kph
  - sensor.pws_alerts
  - sensor.pws_location
  - sensor.pws_observation_time
  - sensor.pws_visibility_km
  - sensor.pws_heat_index_c
  - sensor.pws_dewpoint_c
  - sensor.pws_elevation
  - sensor.pws_precip_1hr_metric
  - sensor.pws_precip_today_metric
  - sensor.pws_pressure_mb
  - sensor.pws_pressure_trend
  - sensor.pws_station_id
  - sensor.pws_solarradiation
  - sensor.pws_uv
  - sensor.pws_wind_degrees

bedroom:
  name: Bedroom
  icon: mdi:hotel
  entities:
  - light.bedroom
  - switch.air_conditioner
  - group.netatmo_indoor
  - group.jon
  - media_player.bedroom_home
  - group.bedroom_sensors

office_sensors:
  name: Office Sensors
  entities:
  - binary_sensor.motion_sensor_158d0001d92086
  - sensor.humidity_158d0001c2c208
  - sensor.temperature_158d0001c2c208

office_view:
  name: Office
  icon: mdi:desktop-mac
  entities:
  - light.office
  - switch.wake_on_lan
  - group.office_sensors

harmony:
  name: Harmony
  entities:
  - sensor.living_room_activity
  - input_select.harmony

dyson_fan:
  name: Dyson Pure Hot+Cool
  entities:
  - fan.kitchen
  - sensor.kitchen_temperature
  - sensor.kitchen_humidity

a_living_room_panel:
  name: Controls
  entities:
  - light.dining_table
  - light.coffee_table
  - light.kitchen
  - light.rear
  - cover.curtain_158d0001ef4394_2
 
living_room_view:
  name: Living Room
  icon: mdi:sofa
  entities:
  - group.a_living_room_panel
  - camera.livingroom_camera
  - group.dyson_fan
  - group.harmony
  - group.xiaomi_gateway
  - media_player.integra
  - media_player.shield
  - media_player.shield_android_tv
  - media_player.plex
  - media_player.blackmagic
  - media_player.kitchen_speaker

bathroom_view:
  name: Bathroom
  icon: mdi:human-male-female
  entities:
  - light.bathroom
  - group.bathroom_sensors

garage:
  name: Garage
  icon: mdi:garage
  entities:
    - group.garage_group
    - group.garage_sensors

laundry_view:
  name: Laundry
  icon: mdi:washing-machine
  entities:
  - group.laundry_group

xiaomi_gateway:
  name: Xiaomi Gateway
  icon: mdi:router-wireless
  entities:
  - sensor.illumination_7811dc6c8ece
  - light.gateway_light_7811dc6c8ece

weather_view:
  name: Weather
  icon: mdi:cloud
  entities:
  - group.ring
  - group.netatmo_indoor
  - group.bedroom_sensors
  - group.office_sensors
  - group.garage_sensors
  - group.netatmo_outdoor
  - group.wunderground  

cameras_view:
  name: Cameras
  icon: mdi:camera
  entities:
  - camera.livingroom_camera
  - camera.last_ring_video
  - camera.backyard
  - camera.side
  - camera.garage

bedroom_sensors:
  name: Bedroom Sensors
  entities:
  - sensor.aeotec_multisensor_motion_template_2
  - sensor.aeotec_zw100_multisensor_6_luminance_2
  - sensor.aeotec_zw100_multisensor_6_relative_humidity_2
  - sensor.aeotec_zw100_multisensor_6_temperature_2
  - sensor.aeotec_zw100_multisensor_6_ultraviolet_2

garage_sensors:
  name: Garage Sensors
  entities:
  - sensor.garage_door_status
  - sensor.garage_door_state
  - sensor.aeotec_multisensor_motion_template_usb
  - sensor.aeotec_zw100_multisensor_6_usb_luminance
  - sensor.aeotec_zw100_multisensor_6_usb_relative_humidity
  - sensor.aeotec_zw100_multisensor_6_usb_temperature
  - sensor.aeotec_zw100_multisensor_6_usb_ultraviolet

jon:
  name: Jon
  entities:
  - binary_sensor.jon_is_home
  - device_tracker.jon_mobile_2
  - input_boolean.jon_sleeping

laundry_group:
  name: Laundry
  entities:
  - switch.plug_158d00019d0f86
  - binary_sensor.door_window_sensor_158d0001c2e60e
  - light.laundry
  
overview:
  name: ' Overview'
  entities:
  - sensor.power_usage
  - cover.curtain_158d0001ef4394_2
  - sensor.netatmo_indoor_temperature
  - sensor.netatmo_indoor_humidity
  - switch.air_conditioner
  - sensor.netatmo_outdoor_temperature
  - sensor.netatmo_outdoor_humidity
  - light.entry_light_level
  - sensor.garage_door_state
  - cover.the_bat_cave
  - vacuum.xiaomi_vacuum_cleaner 
  
ups:
  name: UPS
  icon: mdi:battery
  entities:
  - sensor.nut_ups_status_data
  - sensor.nut_ups_load
  - sensor.nut_ups_nominal_real_power
  - sensor.nut_ups_battery_charge
  - sensor.nut_ups_battery_runtime
  - sensor.nut_ups_low_battery_runtime
  - sensor.nut_ups_battery_temperature
  - sensor.nut_ups_battery_voltage
  - sensor.nut_ups_nominal_battery_voltage
  - sensor.nut_ups_input_voltage
  - sensor.nut_ups_nominal_input_voltage

bathroom_sensors:
  name: Bathroom Sensors
  entities:
  - sensor.temperature_158d0001fead1f
  - sensor.humidity_158d0001fead1f
  - binary_sensor.motion_sensor_158d00015a83dd

zigbee_group:
  name: Xiaomi Switches
  icon: mdi:router-wireless
  entities:
  - binary_sensor.switch_158d0001d8dbde
  - binary_sensor.wall_switch_both_158d0001641a34
  - binary_sensor.wall_switch_left_158d0001641a34
  - binary_sensor.wall_switch_right_158d0001641a34
  - binary_sensor.smoke_sensor_158d0001641a34

door_sensors:
  name: Doors
  icon: mdi:door
  entities:
  - binary_sensor.door_window_sensor_158d00020193e4
  - binary_sensor.glass_door_sensor
  - binary_sensor.door_window_sensor_158d0001c2e60e
  - binary_sensor.door_window_sensor_158d0001fd6e59

default_view:
  name: Home
  icon: mdi:home
  entities:
  - group.alarm
  - group.lights
  - group.overview
  - group.door_sensors
  - group.jon
  - media_player.galaxy_s8
  - group.motion_sensors

alarm:
  name: Alarm Panel
  entities:
  - alarm_control_panel.home_alarm

automation:
  name: Automation
  icon: mdi:auto-fix
  entities:
  - group.all_scenes
  - group.all_automations
  - group.all_scripts
  - group.overrides

battery_status:
  name: Battery Status
  icon: mdi:battery-charging
  entities:
  - sensor.bathroom_humidity_battery
  - sensor.bathroom_temperature_battery
  - sensor.bedside_switch_battery
  - sensor.cube_158d0001038d6d_battery
  - sensor.door_sensor_front_battery
  - sensor.door_sensor_garage_rear_battery
  - sensor.door_sensor_glass_rear_battery
  - sensor.entry_sensor_battery
  - sensor.garage_sensor_battery
  - sensor.insect_plug_battery
  - sensor.living_room_curtains_battery
  - sensor.motion_sensor_bathroom_battery
  - sensor.motion_sensor_office_battery
  - sensor.netatmo_outdoor_battery
  - sensor.nut_ups_battery_temperature
  - sensor.office_humidity_battery
  - sensor.office_temperature_battery
  - sensor.ring_front_door_horseshoe_cct_battery
  - sensor.wall_switch_both_battery
  - sensor.wall_switch_left_battery
  - sensor.wall_switch_right_battery
  - sensor.washing_machine_plug_battery
  - sensor.water_leak_sensor_158d0001c34822_battery
  - sensor.xiaomi_vacuum_cleaner_battery

batteries_view:
  name: Batteries
  icon: mdi:battery-charging
  entities:
  - group.battery_alert
  - group.battery_status
  - group.ups

motion_sensors:
  name: Motion
  icon: mdi:walk
  entities:
  - binary_sensor.motion_sensor_158d0001e08ece
  - binary_sensor.motion_sensor_158d0001d92086
  - sensor.ring_front_door_horseshoe_cct_last_motion
  - sensor.aeotec_multisensor_motion_template_2
  - sensor.aeotec_multisensor_motion_template_usb
  - binary_sensor.motion_sensor_158d00015a83dd
