- id: jon_leave
  alias: Jon Leaving
  trigger:
  - entity_id: binary_sensor.jon_is_home
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.disable_auto_presence
    state: 'off'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - entity_id: scene.all_off
    service: scene.turn_on
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away
  initial_state: true
  hide_entity: false
- action:
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
  alias: Jon Arriving Home
  condition: []
  id: '1515407554216'
  trigger:
  - entity_id: binary_sensor.jon_is_home
    from: 'off'
    platform: state
    to: 'on'
- id: '1516741880050'
  alias: Vacuum On with Alarm
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: cleaning
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
  - delay: '5'
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_home
- id: '1516741880051'
  alias: Vacuum Off with Alarm
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: docked
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_home
  action:
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
  - delay: '5'
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away