- id: jon_leave
  alias: Jon Leaving
  trigger:
  - entity_id: binary_sensor.jon_is_home
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.disable_auto_presence
    state: 'off'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - entity_id: scene.all_off
    service: scene.turn_on
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away
  initial_state: true
  hide_entity: false
- action:
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
  alias: Jon Arriving Home
  condition: []
  id: '1515407554216'
  trigger:
  - entity_id: binary_sensor.jon_is_home
    from: 'off'
    platform: state
    to: 'on'
- id: '1515663327938'
  alias: Bathroom Movement Day
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00015a83dd
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - data:
      brightness_pct: 100
      color_temp: 370
      entity_id: light.bathroom
    service: light.turn_on
  - data:
      entity_id: script.motion_bathroom_timer
    service: script.turn_off
- id: '1516741880050'
  alias: Vacuum On with Alarm
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: cleaning
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
  - delay: '5'
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_home
- id: '1516741880051'
  alias: Vacuum Off with Alarm
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: docked
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_home
  action:
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
  - delay: '5'
  - data:
      code: !secret alarm_code
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away
- id: '1521148590273'
  alias: Vacuum while at work
  trigger:
  - entity_id: device_tracker.jon_mobile_2
    platform: state
    to: Work
  condition:
  - after: 08:00
    before: '10:30'
    condition: time
  action:
  - data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.start
- id: '1526219825995'
  alias: Jon Waking Up
  trigger:
  - entity_id: input_boolean.jon_sleeping
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - above: '50'
    condition: numeric_state
    entity_id: sensor.pws_solarradiation
  action:
  - data:
      entity_id: cover.curtain_158d0001ef4394_2
    service: cover.open_cover
- id: '1526899238902'
  alias: Curtain Close Sunset
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: cover.curtain_158d0001ef4394_2
    state: open
  - below: '23'
    condition: numeric_state
    entity_id: sensor.kitchen_temperature
  - above: '0'
    condition: numeric_state
    entity_id: sensor.comparison_temperature
  action:
  - data:
      entity_id: cover.curtain_158d0001ef4394_2
    service: cover.close_cover
- id: '1526900784652'
  alias: Curtain Close Cooling
  trigger:
  - above: '23'
    entity_id: sensor.kitchen_temperature
    platform: numeric_state
  condition:
  - below: '0'
    condition: numeric_state
    entity_id: sensor.comparison_temperature
  action:
  - data:
      entity_id: cover.curtain_158d0001ef4394_2
    service: cover.close_cover
- id: '1526901262371'
  alias: Curtain Close Heating
  trigger:
  - below: '50'
    entity_id: sensor.aeotec_zw100_multisensor_6_usb_ultraviolet
    platform: numeric_state
  condition:
  - condition: state
    entity_id: cover.curtain_158d0001ef4394_2
    state: open
  - above: '0'
    condition: numeric_state
    entity_id: sensor.comparison_temperature
  action:
  - data:
      entity_id: cover.curtain_158d0001ef4394_2
    service: cover.close_cover
- id: '1528695583677'
  alias: Bedroom Movement Day
  trigger:
  - entity_id: sensor.aeotec_multisensor_motion_template_2
    platform: state
    to: motion detected
  condition:
  - after: sunrise
    before: sunset
    condition: sun
  - condition: state
    entity_id: input_boolean.jon_sleeping
    state: 'off'
  action:
  - data:
      brightness_pct: '60'
      color_temp: 370
      entity_id: light.bedroom
    service: light.turn_on
- id: '1528695583678'
  alias: Bedroom Movement Night
  trigger:
  - entity_id: sensor.aeotec_multisensor_motion_template_2
    platform: state
    to: motion detected
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: input_boolean.jon_sleeping
    state: 'off'
  action:
  - data:
      brightness_pct: '20'
      color_temp: 154
      entity_id: light.bedroom
    service: light.turn_on
- id: '1528695583679'
  alias: Bedroom Movement Sleeping
  trigger:
  - entity_id: sensor.aeotec_multisensor_motion_template_2
    platform: state
    to: motion detected
  condition:
  - condition: state
    entity_id: input_boolean.jon_sleeping
    state: 'on'
  action: []
- id: '1528695981619'
  alias: Bedroom No Movement
  trigger:
  - entity_id: sensor.aeotec_multisensor_motion_template_2
    platform: state
    to: standby
  condition: []
  action:
  - data:
      entity_id: light.bedroom
    service: light.turn_off
- id: '1528705374761'
  alias: Garage Auto Open
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00020193e4
    platform: state
    to: 'on'
  condition:
  - after: 07:00
    before: '10:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: binary_sensor.garage_door
    state: 'off'
  - condition: zone
    entity_id: device_tracker.jon_mobile_2
    zone: zone.home
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - data:
      entity_id: switch.garage_door
    service: switch.turn_on
  - data:
      entity_id: media_player.kitchen_speaker
      message: Enjoy your day.  Opening the garage door!
    service: tts.google_translate_say
- id: '1528705714166'
  alias: Garage Door Auto Close
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00020193e4
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.garage_door
    state: 'on'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - data:
      entity_id: switch.garage_door
    service: switch.turn_off
  - data:
      entity_id: media_player.kitchen_speaker
      message: Welcome home.  Closing the garage door!
    service: tts.google_translate_say
- id: '1548314269286'
  alias: Turn Off Jon Sleeping
  trigger:
  - platform: webhook
    webhook_id: jon-sleeping-off
  condition: []
  action:
  - data:
      entity_id: input_boolean.jon_sleeping
    service: input_boolean.turn_off
- id: '1548314269283'
  alias: Turn On Jon Sleeping
  trigger:
  - platform: webhook
    webhook_id: jon-sleeping-on
  condition: []
  action:
  - data:
      entity_id: input_boolean.jon_sleeping
    service: input_boolean.turn_on
- id: '1566101430559'
  alias: Entry Movement
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e08ece
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.jon_sleeping
    state: 'off'
  - after: sunrise
    before: sunset
    condition: sun
  action:
  - data:
      brightness: 255
      color_temp: 327
      entity_id: light.entry_light_level
    service: light.turn_on
- id: '1566101796883'
  alias: Entry Movement Evening
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e08ece
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.jon_sleeping
    state: 'off'
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - data:
      brightness: 255
      entity_id: light.entry_light_level
      xy_color:
      - 0.542
      - 0.392
    service: light.turn_on
