- alias: Harmony
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Select Input'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "nVidia Shield") %}
            22486705
          {% elif is_state("input_select.harmony", "Play XBox One") %}
            6761513
          {% elif is_state("input_select.harmony", "Control PS4") %}
            15118032
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"
