# Thanks to JesseWebDotCom - https://github.com/JesseWebDotCom/home-assistant-configuration/blob/master/packages/ha.yaml
homeassistant:
  customize:
    script.backup:
      icon: mdi:zip-box
      friendly_name: Backup Home Assistant

shell_command:
  # BACKUP - 1 FILE PER DAY
  backup: 7z u -r "/mnt/NASJB/backup/HomeAssistant/backup-$(date +"%Y%m%d").7z" /home/homeassistant/.homeassistant

script:
  backup:
    alias: Backup Home Assistant
    sequence:
      - service: shell_command.backup_zip
