binary_sensor:
  - platform: 'bayesian'
    prior: 0.75
    name: 'Jon is Home'
    probability_threshold: 0.90
    observations:
      - entity_id: 'device_tracker.jon_mobile'
        prob_given_true: 0.95
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.my_s8_mobile'
        prob_given_true: 1
        prob_given_false: 0.8
        platform: 'state'
        to_state: 'home'
# https://community.home-assistant.io/t/best-implementation-strategy-for-bayesian-binary-sensor/22673/15
