remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.3
    activity: 22486705

sensor:
  - platform: template
    sensors:
      living_room_activity:
        value_template: '{{ states.remote.living_room.attributes.current_activity }}'
        friendly_name: "Living Room Activity"

input_select:
  harmony:
    name: Harmony Control
    options:
### DO NOT REMOVE 'SELECT INPUT'
      - Select Input
      - Use PC
      - nVidia Shield
      - Play XBox One
      - Control PS4
      - Power Off
    icon: mdi:monitor
