sensor:
  - platform: nut
    host: 192.168.1.10
    resources:
      - ups.status
      - ups.load
      - ups.realpower.nominal
      - battery.charge
      - battery.runtime
      - battery.runtime.low
      - battery.temperature
      - battery.voltage
      - battery.voltage.nominal
      - input.voltage
      - input.voltage.nominal
